apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: otel-collector-otlp
spec:
  access:
  - users:
    - '*'
    verbs:
    - get
  config:
    chart:
      name: opentelemetry-collector
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      version: 0.80.1
    values: |
      ---
      mode: daemonset
      presets:
        kubeletMetrics:
          enabled: true
        kubernetesAttributes:
          enabled: true
      service:
        enabled: true
      # Explicitly inject node name for local-only scraping
      extraEnvs:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      config:
        receivers:
          kubeletstats:
            insecure_skip_verify: "{{ .Values.prometheus.insecure }}"
        processors:
          attributes:
            actions:
            - action: upsert
              key: cluster
              value: "{{ .Values.loft.cluster }}"
            - action: upsert
              key: loft_project_name
              value: "{{ .Values.loft.project }}"
            - action: upsert
              key: loft_virtualcluster_name
              value: "{{ .Values.loft.name }}"
            - action: upsert
              key: loft_user_name
              value: "{{ .Values.loft.user.name }}"
          transform:
            error_mode: ignore
            metric_statements:
              context: datapoint
              statements:
              - 'set(attributes["k8s.node.name"], resource.attributes["k8s.node.name"])'
              - 'set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"])'
              - 'set(attributes["k8s.namespace.name"], resource.attributes["k8s.namespace.name"])'
          memory_limiter:
            check_interval: 1s
            limit_percentage: 75
            spike_limit_percentage: 15
          batch:
            send_batch_size: 10000
            timeout: 10s
        exporters:
          otlphttp/prometheus:
            endpoint: '{{ .Values.prometheus.endpoint }}/api/v1/otlp'
            tls:
              insecure_skip_verify: "{{ .Values.prometheus.insecure }}"
        service:
          extensions:
          - health_check
          pipelines:
            metrics:
              receivers:
              - kubeletstats
              processors:
              - memory_limiter
              - k8sattributes
              - attributes
              - transform
              - batch
              exporters:
              - otlphttp/prometheus
  defaultNamespace: monitoring
  description: |
    Lightweight OpenTelemetry Collector using kubeletstats receiver only.
    Uses OTel semantic conventions for metric names (k8s_*, container_*).
    Simpler config with minimal RBAC requirements. Use with vcluster-prv-dashboard-small.json.
    Note: Does not include API server metrics, kubelet operational metrics, or container-level granularity.
  displayName: OTEL Collector - OTLP
  icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
  parameters:
  - description: The Prometheus endpoint to push metrics to
    label: Prometheus Endpoint
    required: true
    variable: prometheus.endpoint
  - description: The Prometheus username
    label: Prometheus Username
    variable: prometheus.username
  - description: The password to access Prometheus
    label: Prometheus Password
    type: password
    variable: prometheus.password
  - description: Skip TLS verification for the connection to Prometheus
    label: Prometheus Skip TLS Verification
    type: boolean
    variable: prometheus.insecure
  recommendedApp:
  - virtualcluster
